# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2527b3fb59dc615c330a838b88916aa1864b1d1d957ebe34aa4c96a123f1f80b7fc4a305a5241b1dfa0f74581b2113fc11e446f7928a59559187a1776f7615a7

test:
  secret_key_base: c59606c2f0e6041a3757bdd7e8bf500747047137bfb19cf45e4722f15223c6f3377fd835a5cb5a29a2be3459186798638aaa71582a991f9b3a570ba7b74f6a22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
